# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20180607_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Getpwd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
